# Convert xlsx to csv

In [1]:
import pandas as pd

In [6]:
df = pd.read_excel('mandatory_11.25B.xlsx', 'car_brand')
df = df.iloc[:,:]
df['model'] = df['model'].astype(str)
df['nickname'] = df['nickname'].astype(str)
df.head()

,car_brand,model,car_model,car_grade,model_th,car_model_th,car_grade_th,nickname
0,-,-,NaN,NaN,-,NaN,NaN,-
1,ALFA ROMEO,145,NaN,NaN,145,NaN,NaN,โฉมปี 1994-2000
2,ALFA ROMEO,146,NaN,NaN,146,NaN,NaN,โฉมปี 1994-2000
3,ALFA ROMEO,155,NaN,NaN,155,NaN,NaN,โฉมปี 1992-1998
4,ALFA ROMEO,156,NaN,NaN,155,NaN,NaN,โฉมปี 1997-2007

In [22]:
# c = df['model'][0]
# c = c.replace(",","").split()
# c

['SERIES', '3', 'ActiveHybrid', '3']

In [7]:
count_model = df['model'].apply(lambda x: len(x.replace(",","").split()))
count_nickname = df['nickname'].apply(lambda x: x.startswith("โฉมปี")).astype(int)
total = count_model + count_nickname
df['total'] = total
df = df.sort_values('total', ascending=False)
df.to_csv('mandatory_edited.csv', index=False)

# Read csv

In [2]:
df = pd.read_csv('mandatory_edited.csv')
df

,car_brand,model,car_model,car_grade,model_th,car_model_th,car_grade_th,nickname,total
0,BMW,"SERIES 3, ActiveHybrid 3",SERIES 3,ActiveHybrid 3,"ซีรี่ย์3, แอคทีฟไฮบริด 3",ซีรี่ย์3,แอคทีฟไฮบริด 3,โฉมปี 2011-2019 (F30),5
1,BMW,"SERIES 7, ActiveHybrid 7",SERIES 7,ActiveHybrid 7,"ซีรี่ย์7, แอคทีฟไฮบริด 7",ซีรี่ย์7,แอคทีฟไฮบริด 7,โฉมปี 2010-2012 (F04),5
2,BMW,"SERIES 5, 535i",SERIES 5,535i,"ซีรี่ย์5, 535ไอ",ซีรี่ย์5,535ไอ,โฉมปี 2010-2017 (F10),4
3,BMW,"SERIES 5, 520i",SERIES 5,520i,"ซีรี่ย์5, 520ไอ",ซีรี่ย์5,520ไอ,โฉมปี 1987-1996 (E34),4
4,BMW,"SERIES 5, 520i",SERIES 5,520i,"ซีรี่ย์5, 520ไอ",ซีรี่ย์5,520ไอ,โฉมปี 2003-2010 (E60),4
...,...,...,...,...,...,...,...,...,...
1212,LAND ROVER,-,NaN,NaN,-,NaN,NaN,-,1
1213,LAND ROVER,DEFENDER,NaN,NaN,ดีเฟนเดอร์,NaN,NaN,-,1
1214,LAND ROVER,DISCOVERY,NaN,NaN,ดิสคัฟเวอรี่,NaN,NaN,-,1
1215,LAND ROVER,FREELANDER,NaN,NaN,ฟรีแลนเดอร์,NaN,NaN,-,1
1216,VOLVO,XC90,NaN,NaN,เอ็กซ์ซี90,NaN,NaN,-,1

In [11]:
mazda = df['car_brand'] == 'MAZDA'
df_mazda = df[mazda]
df_mazda

,car_brand,model,car_model,car_grade,model_th,car_model_th,car_grade_th,nickname,total
183,MAZDA,BT-50 PRO,NaN,NaN,บีที-50 โปร,NaN,NaN,"โฉมปี 2012-2018 (2WD, 4WD, HI-RACER ยกสูง)",3
184,MAZDA,626 Cronos,NaN,NaN,626โครโนส,NaN,NaN,โฉมปี 1992-1997,3
185,MAZDA,323 PROTEGE,NaN,NaN,323โปรเทเจ้,NaN,NaN,โฉมปี 2000-2006,3
252,MAZDA,MAZDA2,NaN,NaN,มาสด้า2,NaN,NaN,โฉมปี 2014-2018 (SKY),2
253,MAZDA,MAZDA2,NaN,NaN,มาสด้า2,NaN,NaN,โฉมปี 2013-2016 (KE),2
...,...,...,...,...,...,...,...,...,...
1076,MAZDA,BT-50,NaN,NaN,บีที-50,NaN,NaN,-,1
1077,MAZDA,CX-3,NaN,NaN,ซีเอ๊กซ์-3,NaN,NaN,-,1
1078,MAZDA,TITAN,NaN,NaN,ไททัน,NaN,NaN,-,1
1079,MAZDA,TRIBUTE,NaN,NaN,ทริบิวต์,NaN,NaN,-,1
1080,MAZDA,XEDOS,NaN,NaN,เซดอส,NaN,NaN,-,1

In [12]:
def categorize_part(part, df_mazda):
    partset = set(word.strip("(),'") for word in part.split())
    for idx, row in df_mazda.iterrows():
        keys = row['model'].split()
        found = all(key in partset for key in keys)
    #     found = True
    #     for key in keys:
    #         if not key in partset:
    #             found = False
    #             break
        if not found:
            continue
        has_year = row['nickname'].startswith("โฉมปี")
        if has_year:
            year = row['nickname'][5:].strip()
            start, end = year.split('-')
            end = end.split(' ')[0]
            start, end = int(start), int(end)
    #         print(start, end)
            found = any(word.isdigit() and start <= int(word) <= end for word in partset)
    #         for word in partset:
    #             if word.isdigit() and start <= int(word) <= end:
    #                 found2 = True
    #                 break
    #         found &= found2
        if found:
    #         print(row)
#             print(row['model'])
#             print(row['model_th'])
#             print(row['nickname'])
            fitment = ''
            if 'FR' in partset:
                fitment = 'หน้า'
            elif 'RE' in partset:
                fitment = 'หลัง'
            return row['model'], row['model_th'], row['nickname'], fitment
    return '','','',''

In [11]:
part = "323 SEDAN 2000 (PROTEGE) RE"
categorize_mazda_part(part, df_mazda)

('323 PROTEGE', '323โปรเทเจ้', 'โฉมปี 2000-2006', 'หลัง')

# Clean data

In [12]:
noclean = pd.read_excel('RBI_No_clean.xlsx')
# noclean['product_internal_code2'] = noclean['product_internal_code2'].astype(str)
noclean

,product_code,product_group,product_internal_code1,product_internal_code2,name,sales_perbox_uom,product_brand,sales_price1
0,124CP1W,บุชปีกนก ล่าง,KD101 34 460,NaN,"FESTIVA, ASPIRE",10,FORD,60
1,127F01E,สกรูกันโคลง,2M51 5E 494AB,NaN,FORD FOCUS RE,10,FORD,120
2,310M010,แท่นเครื่อง,12361-87206,12371-87209,MIRA FR RE,4,DAIHATSU,110
3,310M020,แท่นเครื่อง,12361-87314,NaN,DAIHATSU,2,DAIHATSU,290
4,311M010,แท่นเกียร์,12373-87203,NaN,MIRA,4,DAIHATSU,150
...,...,...,...,...,...,...,...,...
3872,T09Z17LAZ,แท่นเครื่อง (ขา),12372-0T211-IN,NaN,"ALTIS ZRE171,172 LH A/T",1,TOYOTA,650
3873,T09Z17LMZ,แท่นเครื่อง (ขา),12372-0T201-IN,NaN,"ALTIS ZRE171,172 LH M/T",1,TOYOTA,650
3874,T24RV04P,บุชปีกนก บน,48632-0K070,NaN,REVO 4WD,4,TOYOTA,150
3875,T18PRV02LR,กันฝุ่นแร็ค (PP+EPDM),45535-09380-P,NaN,"REVO 2WD LH, RH",2,TOYOTA,140
3876,T18PRV04LR,กันฝุ่นแร็ค (PP+EPDM),45535-09390-P,NaN,"REVO 4WD LH, RH",2,TOYOTA,140

In [13]:
noclean = noclean[noclean['product_brand'] == 'MAZDA']
noclean

,product_code,product_group,product_internal_code1,product_internal_code2,name,sales_perbox_uom,product_brand,sales_price1
44,D0936E,บุชยึดเครื่อง,BR74 39 040,NaN,323 SEDAN 92 RE,4,MAZDA,150
45,D0936EZ,แท่นเครื่อง (ขา),BR74 39 040-IN,NaN,323 SEDAN 92 RE,2,MAZDA,270
46,D0936F,บุชยึดเครื่อง,B455 39 050B,NaN,323 SEDAN 92 FR,4,MAZDA,170
47,D0936FZ,แท่นเครื่อง (ขา),B455 39 050B-IN,NaN,323 SEDAN 92 FR,2,MAZDA,300
48,D0936L,บุชยึดเครื่อง,B455 39 100E,NaN,323 SEDAN 92 LH,4,MAZDA,170
...,...,...,...,...,...,...,...,...
3859,D13CX12E,เบ้าโช้คอัพ,KD45 28 910J-2,NaN,CX5 2012 RE,10,MAZDA,80
3860,D17CX12BFI,กันฝุ่นเพลา ใน,GG62 22 540,NaN,CX5 2012 (B) FR,2,MAZDA,110
3861,D17CX12DFU,กันฝุ่นเพลา นอก,FTB4 22 530,NaN,CX5 2012 (D) FR,2,MAZDA,120
3862,D25CX1235,บุชคาน,KD35 28 350-0,KD35 28 621,CX5 2012 RE,6,MAZDA,150
3863,D26CX12E,บุชโช้คอัพ,KD45 28 910J-1,NaN,CX5 2012 RE,6,MAZDA,100

In [14]:
rows = []
for idx, row in noclean.iterrows():
#     print(row)
    code = row['product_internal_code1']
    code2 = row['product_internal_code2']
    if not pd.isnull(code2):
        code += ' , ' + str(code2)
    part = str(row['name'])
    model, model_th, nick, fitment = categorize_mazda_part(part, df_mazda)
    rowc = [row['product_code'], code, 'MAZDA', part, model, model_th, nick, row['product_group'], fitment]
    rows.append(rowc)
clean = pd.DataFrame(rows, columns=['Supplier_NO.', 'OEM_NO.', 'car_brand', 'name', 'car_model', 'model_name_th', 'nickname', 'item_name', 'fitment_detail'])
clean

,Supplier_NO.,OEM_NO.,car_brand,name,car_model,model_name_th,nickname,item_name,fitment_detail
0,D0936E,BR74 39 040,MAZDA,323 SEDAN 92 RE,323,323,-,บุชยึดเครื่อง,หลัง
1,D0936EZ,BR74 39 040-IN,MAZDA,323 SEDAN 92 RE,323,323,-,แท่นเครื่อง (ขา),หลัง
2,D0936F,B455 39 050B,MAZDA,323 SEDAN 92 FR,323,323,-,บุชยึดเครื่อง,หน้า
3,D0936FZ,B455 39 050B-IN,MAZDA,323 SEDAN 92 FR,323,323,-,แท่นเครื่อง (ขา),หน้า
4,D0936L,B455 39 100E,MAZDA,323 SEDAN 92 LH,323,323,-,บุชยึดเครื่อง,
...,...,...,...,...,...,...,...,...,...
336,D13CX12E,KD45 28 910J-2,MAZDA,CX5 2012 RE,,,,เบ้าโช้คอัพ,
337,D17CX12BFI,GG62 22 540,MAZDA,CX5 2012 (B) FR,,,,กันฝุ่นเพลา ใน,
338,D17CX12DFU,FTB4 22 530,MAZDA,CX5 2012 (D) FR,,,,กันฝุ่นเพลา นอก,
339,D25CX1235,"KD35 28 350-0 , KD35 28 621",MAZDA,CX5 2012 RE,,,,บุชคาน,
340,D26CX12E,KD45 28 910J-1,MAZDA,CX5 2012 RE,,,,บุชโช้คอัพ,

In [10]:
clean.to_csv('clean2.csv')