In [1]:
import pandas as pd

In [2]:
rev_atp = pd.read_excel('autopair_rev15.13B.xlsx')
car_brand = pd.read_excel('mandatory_11.27_tomew.xlsx', 'car_brand')
item_cat = pd.read_excel('mandatory_11.27_tomew.xlsx', 'item_cat')
item_brand = pd.read_excel('mandatory_11.27_tomew.xlsx', 'item_brand')
stock_uom = pd.read_excel('mandatory_11.27_tomew.xlsx', 'stock_uom')
fitment_detail = pd.read_excel('mandatory_11.27_tomew.xlsx', 'fitment_detail')

In [3]:
rev_atp.head()

,Supplier_NO.,car_brand,car_model,model_name_th,nickname,item_name,fitment_detail,description,brand,item_group,stock_uom,CC
0,NaN,AUDI,Q5,คิว5,โฉมปี 2008-2016,ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN
1,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),เบ้าโช้คอัพ/ยางเบ้าโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น,NaN
2,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2003-2010 (E60),ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN
3,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),ยางกันกระแทกโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น,NaN
4,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2010-2017 (F10),ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN

In [4]:
rev_atp['index'] = range(1, len(rev_atp) + 1)
rev_atp = rev_atp.set_index('index')
rev_atp

,Supplier_NO.,car_brand,car_model,model_name_th,nickname,item_name,fitment_detail,description,brand,item_group,stock_uom,CC
index,,,,,,,,,,,,
1,NaN,AUDI,Q5,คิว5,โฉมปี 2008-2016,ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN
2,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),เบ้าโช้คอัพ/ยางเบ้าโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น,NaN
3,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2003-2010 (E60),ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN
4,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),ยางกันกระแทกโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น,NaN
5,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2010-2017 (F10),ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
46568,KAG1002 (343326-D) (172207),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD (GAS),ADD,-,ชิ้น,NaN
46569,KAA-7002 (444135-D) (180187),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD(OIL),ADD,-,ชิ้น,NaN
46570,KAG2012 (344305-D) (173036),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,หน้า,โช๊คอัพ F FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น,NaN
46571,KAG2011 (344304-D) (173167),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น,NaN
46572,KAA-2002 (444136-D) (180188),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(OIL),ADD,-,ชิ้น,NaN

In [5]:
car_brand = car_brand.rename({'car_brand': 'brand', 'nickname': 'name', 'car_model': 'model', 'model_name_th': 'model_th'}, axis=1)
car_brand = car_brand.astype(str)
print(car_brand.keys())
car_brand

Index(['brand', 'model', 'model_th', 'name'], dtype='object')

,brand,model,model_th,name
0,OTHER BRAND,Other model,รุ่นอื่นๆ,(โปรดระบุยี่ห้อและรุ่นในรายละเอียดสินค้า)
1,-,-,-,-
2,ALFA ROMEO,145,145,โฉมปี 1994-2000
3,ALFA ROMEO,146,146,โฉมปี 1994-2000
4,ALFA ROMEO,155,155,โฉมปี 1992-1998
...,...,...,...,...
1210,VOLVO,V70,วี70,-
1211,VOLVO,V70R,วี70R,-
1212,VOLVO,XC,เอ็กซ์ซี,-
1213,VOLVO,XC60,เอ็กซ์ซี60,-
1214,VOLVO,XC90,เอ็กซ์ซี90,-

In [6]:
rev_atp2 = rev_atp.iloc[:,1:5].astype(str)
rev_atp2 = rev_atp2.rename({'car_brand' : 'carbrand',}, axis=1)
print(rev_atp2.keys())
rev_atp2

Index(['carbrand', 'car_model', 'model_name_th', 'nickname'], dtype='object')

      carbrand car_model model_name_th                           nickname
index
1         AUDI        Q5          คิว5                    โฉมปี 2008-2016
2       TOYOTA     CAMRY        คัมรี่            โฉมปี 2002-2006 (ACV30)
3          BMW  SERIES 5      ซีรี่ย์5              โฉมปี 2003-2010 (E60)
4       TOYOTA     CAMRY        คัมรี่            โฉมปี 2002-2006 (ACV30)
5          BMW  SERIES 5      ซีรี่ย์5              โฉมปี 2010-2017 (F10)
...        ...       ...           ...                                ...
46568     FORD    RANGER      แรนเจอร์  โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)
46569     FORD    RANGER      แรนเจอร์  โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)
46570     FORD    RANGER      แรนเจอร์  โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)
46571     FORD    RANGER      แรนเจอร์  โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)
46572     FORD    RANGER      แรนเจอร์  โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)

[46572 rows x 4 columns]

In [7]:
nickname_test = rev_atp2['nickname'].loc[2]
nickname_test

'โฉมปี 2002-2006 (ACV30)'

In [8]:
car_brand_test = car_brand['name'].iloc[610]
car_brand_test

'โฉมปี 2000-2007 (W203)'

In [9]:
if nickname_test == car_brand_test:
    print('yes')
else:
    print('no')

no

In [10]:
import warnings
warnings.filterwarnings("ignore", 'This pattern has match groups')

In [11]:
def brand_mandatory_rev(df):
    rowA = []
    rowB = []
    rowC = []
    rowD = []

    for idx_row, row in df.iterrows():
        car_brand_finding = row['carbrand']
        car_model_finding = row['car_model']
        model_th_finding = row['model_name_th']
        nickname_finding = row['nickname']

        car_brand_check = car_brand['brand']
        
        car_brandcheck = []
        for brand in  car_brand_check:
            if brand == car_brand_finding:
                car_brandcheck.append(True)
            else:
                car_brandcheck.append(False)
        found = any(j == True for j in car_brandcheck)
        rowA.append(found)
        carA = car_brand
        if found:
            carA = carA[car_brandcheck]
#         print(carA)
#         print(rowA)

        car_model_check = carA['model']
    #         print(carnametest)
        car_modelcheck = []
        for model in car_model_check:
    #             print(i)
            if model == car_model_finding:
    #                 print(i)
                car_modelcheck.append(True)
            else:
                car_modelcheck.append(False)
        found1 = any(a == True for a in car_modelcheck)
        rowB.append(found1)
        carB = carA
        if found1:
            carB = carB[car_modelcheck]
#         print(car)
#         print(rowB)

        model_th_check = carB['model_th']
        modelth_check = []
        for modelth in model_th_check:
            if modelth == model_th_finding:
                modelth_check.append(True)
            else:
                modelth_check.append(False)
        found2 = any(b == True for b in modelth_check)
        rowC.append(found2)
        carC = carB
        if found2:
            carC = carC[modelth_check]
            
    #     print(car)
    # print(rowC)

        if 'name' not in carC:
            print(f"carA:{carA}")
            print(f"carB:{carB}")
            print(f"carC:{carC}")
            print(f"idx_row: {idx_row}")
            print(f"row: {row}")
            print(f"modelth_check: {modelth_check}")
        nicknamecheck = carC['name']
        
        namecheck = []
        for cname in nicknamecheck:
            if cname == nickname_finding:
                namecheck.append(True)
            else:
                namecheck.append(False)
        found3 = any(k == True for k in namecheck)
        rowD.append(found3)
        carD = carC
        if found3:
            carD = carD[namecheck]
            
#         print(car)
#         print(rowD)

    dfA = pd.DataFrame(rowA, columns = ['car_brand'])
    dfB = pd.DataFrame(rowB, columns = ['car_model'])
    dfC = pd.DataFrame(rowC, columns = ['model_name_th'])
    dfD = pd.DataFrame(rowD, columns = ['nickname'])
    ret = pd.concat([dfA,dfB,dfC,dfD], axis=1)
    ret['index'] = range(1, len(ret) + 1)
    ret = ret.set_index('index')
    return ret

In [12]:
carbrand_check = brand_mandatory_rev(rev_atp2)

In [13]:
carbrand_check

       car_brand  car_model  model_name_th  nickname
index
1           True       True           True      True
2           True       True           True      True
3           True       True           True      True
4           True       True           True      True
5           True       True           True      True
...          ...        ...            ...       ...
46568       True       True           True      True
46569       True       True           True      True
46570       True       True           True      True
46571       True       True           True      True
46572       True       True           True      True

[46572 rows x 4 columns]

In [14]:
carbrand_check[~carbrand_check.all(axis=1)]

       car_brand  car_model  model_name_th  nickname
index
36929       True      False          False     False
36930       True      False          False     False
36931       True      False          False     False
36932       True      False          False     False
36933       True      False          False     False
...          ...        ...            ...       ...
46465       True       True           True     False
46469       True       True           True     False
46470       True       True           True     False
46495       True       True           True     False
46496       True       True           True     False

[439 rows x 4 columns]

In [15]:
rev_atp2[~carbrand_check.all(axis=1)]

      carbrand   car_model  model_name_th                 nickname
index
36929   TOYOTA         nan            nan                      nan
36930   TOYOTA         nan            nan                      nan
36931   TOYOTA         nan            nan                      nan
36932   TOYOTA         nan            nan                      nan
36933   TOYOTA         nan            nan                      nan
...        ...         ...            ...                      ...
46465   TOYOTA  HILUX VIGO  ไฮลักซ์ วีโก้                      nan
46469   TOYOTA       CAMRY         คัมรี่  โฉมปี 2006-2011 (ACV40)
46470   TOYOTA  HILUX REVO  ไฮลักซ์ รีโว่                      nan
46495   TOYOTA    COMMUTER    คอมมิวเตอร์  โฉมปี 2004-2019(KDH200)
46496   TOYOTA    COMMUTER    คอมมิวเตอร์  โฉมปี 2004-2019(KDH200)

[439 rows x 4 columns]

In [16]:
# carbrand_check.to_csv('carbrand_check.csv', index=False)

In [17]:
item_cat = item_cat.astype(str)
item_cat

         InLineCategory
0            ผ้าดิสเบรค
1              ก้ามเบรค
2            จานดิสเบรค
3           จานดรัมเบรค
4            กระบอกเบรค
..                  ...
437         ฝาครอบวาล์ว
438   ปั๊มน้ำมันเครื่อง
439       ฝาครอบราวลิ้น
440  เหล็กประกับกันโคลง
441         ปะเก็นฝาสูบ

[442 rows x 1 columns]

In [18]:
itemname = rev_atp.iloc[:,5:6].astype(str)
itemname

                        item_name
index
1            ไส้กรองน้ำมันเครื่อง
2      เบ้าโช้คอัพ/ยางเบ้าโช้คอัพ
3            ไส้กรองน้ำมันเครื่อง
4             ยางกันกระแทกโช้คอัพ
5            ไส้กรองน้ำมันเครื่อง
...                           ...
46568                     โช๊คอัพ
46569                     โช๊คอัพ
46570                     โช๊คอัพ
46571                     โช๊คอัพ
46572                     โช๊คอัพ

[46572 rows x 1 columns]

In [19]:
# item_test = rev_atp['item_name'].iloc[40806]
# item_test

In [20]:
def itemcat_mandatory_rev(df2):
    rowE = []

    for idx_row, row in df2.iterrows():
        item_cat_finding = row['item_name']

        itemcat_check = item_cat['InLineCategory']
        itemcheck = []
        for im in  itemcat_check:
            if im == item_cat_finding:
                itemcheck.append(True)
            else:
                itemcheck.append(False)
        foundG = any(m == True for m in itemcheck)
        rowE.append(foundG)
        itemcatA = item_cat
        if foundG:
            itemcatA = itemcatA[itemcheck]
#         print(itemcatA)
#         print(rowE)
#         if 'name' not in carC:
#             print(f"carA:{carA}")
#             print(f"carB:{carB}")
#             print(f"carC:{carC}")
#             print(f"idx_row: {idx_row}")
#             print(f"row: {row}")
#             print(f"modelth_check: {modelth_check}")

    dfE = pd.DataFrame(rowE, columns = ['item_name'])
    dfE['index'] = range(1, len(dfE) + 1)
    ret3 = dfE.set_index('index')
    return ret3

In [21]:
item_name_check = itemcat_mandatory_rev(itemname)
item_name_check

       item_name
index
1           True
2           True
3           True
4           True
5           True
...          ...
46568      False
46569      False
46570      False
46571      False
46572      False

[46572 rows x 1 columns]

In [22]:
item_name_check[~item_name_check.all(axis=1)]

       item_name
index
1855       False
21369      False
31327      False
33451      False
33867      False
...          ...
46568      False
46569      False
46570      False
46571      False
46572      False

[2648 rows x 1 columns]

In [23]:
itemname[~item_name_check.all(axis=1)]

           item_name
index
1855          ลูกปืน
21369  ลูกหมากคันส่ง
31327         ลูกปืน
33451         ลูกปืน
33867         ลูกปืน
...              ...
46568        โช๊คอัพ
46569        โช๊คอัพ
46570        โช๊คอัพ
46571        โช๊คอัพ
46572        โช๊คอัพ

[2648 rows x 1 columns]

In [24]:
fitment_detail = fitment_detail.astype(str)
fitment_detail

         Fitment
0              -
1           หลัง
2           หน้า
3           ล่าง
4             บน
5             ใน
6            นอก
7        หน้าขวา
8       หน้าซ้าย
9           ซ้าย
10           ขวา
11        ในหน้า
12       หลังขวา
13      หลังซ้าย
14  หลังซ้ายล่าง
15   หลังขวาล่าง
16       นอกซ้าย
17       นอกล่าง
18        ในล่าง
19        ในหลัง
20        ซ้ายบน
21      ซ้ายล่าง
22        ในซ้าย
23         ในขวา
24    หลังซ้ายบน
25     หลังขวาบน
26       นอกหลัง
27       นอกหน้า
28       ขวาล่าง
29         ขวาบน
30          กลาง
31      หน้ากลาง
32        หลังบน
33      หลังล่าง
34        นอกขวา
35      หน้าล่าง
36      หลังใหญ่
37      ล่างเล็ก
38      ล่างใหญ่
39      หลังเล็ก
40        หน้าบน
41      ใหญ่เล็ก
42      บน, ล่าง
43        นอก/ใน
44          เข้า
45           ออก
46        บนหน้า
47        บนหลัง
48  นอก ซ้าย/ขวา
49        นอก-ใน
50       ล่างขวา
51      ล่างซ้าย
52      ล่างหลัง
53       ล่างนอก
54     ล่าง หน้า
55         หลัง
56      ซ้าย,ขวา

In [25]:
fitment = rev_atp.iloc[:,6:7].astype(str)
fitment

      fitment_detail
index
1                  -
2               หน้า
3                  -
4               หน้า
5                  -
...              ...
46568            ขวา
46569            ขวา
46570           หน้า
46571            ขวา
46572            ขวา

[46572 rows x 1 columns]

In [26]:
def fitment_mandatory_rev(df3):
    rowF = []

    for idx_row, row in df3.iterrows():
        fitment_detail_finding = row['fitment_detail']
            
        fitment_check = fitment_detail['Fitment']
        fitmentcheck = []
        for fm in  fitment_check:
            if fitment_detail_finding == "nan":
                fitmentcheck.append(True)
            else:
                if fm == fitment_detail_finding:
                    fitmentcheck.append(True)
                else:
                    fitmentcheck.append(False)
            
        foundF = any(n == True for n in fitmentcheck)
        rowF.append(foundF)
        fitmentA = fitment_detail
        if foundF:
            fitmenttA = fitmentA[fitmentcheck]
#         print(itemcatA)
#         print(rowE)
#         if 'name' not in carC:
#             print(f"carA:{carA}")
#             print(f"carB:{carB}")
#             print(f"carC:{carC}")
#             print(f"idx_row: {idx_row}")
#             print(f"row: {row}")
#             print(f"modelth_check: {modelth_check}")

    dfF = pd.DataFrame(rowF, columns = ['fitment_detail'])
    dfF['index'] = range(1, len(dfF) + 1)
    ret4 = dfF.set_index('index')
    return ret4

In [27]:
fitment_detail_check = fitment_mandatory_rev(fitment)
fitment_detail_check

       fitment_detail
index
1                True
2                True
3                True
4                True
5                True
...               ...
46568            True
46569            True
46570            True
46571            True
46572            True

[46572 rows x 1 columns]

In [28]:
fitment_detail_check[~fitment_detail_check.all(axis=1)]

       fitment_detail
index
37797           False
37798           False
43541           False

In [29]:
fitment[~fitment_detail_check.all(axis=1)]

        fitment_detail
index
37797     หลัง(มีหมุด)
37798  หลัง(ไม่มีหมุด)
43541          ซ้ายขวา

In [30]:
item_brand = item_brand.astype(str)
item_brand

         เกรดสินค้า   brand
0               แท้     แท้
1    เทียบแท้เกรด A  SEIKEN
2    เทียบแท้เกรด A     555
3    เทียบแท้เกรด A     SKF
4    เทียบแท้เกรด A     NSK
..              ...     ...
299               -     GNS
300               -   IMMOS
301               -     ADD
302               -     bbb
303               -   ASSAB

[304 rows x 2 columns]

In [31]:
brand_item_group = rev_atp.iloc[:,8:10].astype(str)
brand_item_group = brand_item_group.rename({'brand': 'item_brand'}, axis=1)
brand_item_group

      item_brand      item_group
index
1           MANN  เทียบแท้เกรด A
2            RBI  เทียบแท้เกรด B
3           MANN  เทียบแท้เกรด A
4            RBI  เทียบแท้เกรด B
5           MANN  เทียบแท้เกรด A
...          ...             ...
46568        ADD               -
46569        ADD               -
46570        ADD               -
46571        ADD               -
46572        ADD               -

[46572 rows x 2 columns]

In [32]:
def itembrand_mandatory_rev(df4):
    rowG = []
    rowH = []

    for idx_row, row in df4.iterrows():
        item_brand_finding = row['item_brand']
        item_group_finding = row['item_group']

        brand_check = item_brand['brand']
        
        brandcheck = []
        for br in  brand_check:
            if br == item_brand_finding:
                brandcheck.append(True)
            else:
                brandcheck.append(False)
        foundG = any(k == True for k in brandcheck)
        rowG.append(foundG)
        itembrandA = item_brand
        if foundG:
            itembrandA = itembrandA[brandcheck]
#         print(itembrandA)
#         print(rowG)

        itemgroup_check = itembrandA['เกรดสินค้า']
    #         print(carnametest)
        item_groupcheck = []
        for item in itemgroup_check:
    #             print(i)
            if item == item_group_finding:
    #                 print(i)
                item_groupcheck.append(True)
            else:
                item_groupcheck.append(False)
        foundH = any(l == True for l in item_groupcheck)
        rowH.append(foundH)
        itembrandB = itembrandA
        if foundH:
            itembrandB = itembrandB[item_groupcheck]
#         print(car)
#         print(rowB)

#         if 'name' not in carC:
#             print(f"carA:{carA}")
#             print(f"carB:{carB}")
#             print(f"carC:{carC}")
#             print(f"idx_row: {idx_row}")
#             print(f"row: {row}")
#             print(f"modelth_check: {modelth_check}")

    dfG = pd.DataFrame(rowG, columns = ['item_brand'])
    dfH = pd.DataFrame(rowH, columns = ['item_group'])
    ret2 = pd.concat([dfG,dfH], axis=1)
    ret2['index'] = range(1, len(ret2) + 1)
    ret2 = ret2.set_index('index')
    return ret2

In [33]:
itembrand_check = itembrand_mandatory_rev(brand_item_group)
itembrand_check

       item_brand  item_group
index
1            True        True
2            True        True
3            True        True
4            True        True
5            True        True
...           ...         ...
46568        True        True
46569        True        True
46570        True        True
46571        True        True
46572        True        True

[46572 rows x 2 columns]

In [34]:
itembrand_check[~itembrand_check.all(axis=1)]

Empty DataFrame
Columns: [item_brand, item_group]
Index: []

In [35]:
brand_item_group[~itembrand_check.all(axis=1)]

Empty DataFrame
Columns: [item_brand, item_group]
Index: []

In [36]:
uom = rev_atp.iloc[:,10:11].astype(str)
uom

      stock_uom
index
1          ชิ้น
2          ชิ้น
3          ชิ้น
4          ชิ้น
5          ชิ้น
...         ...
46568      ชิ้น
46569      ชิ้น
46570      ชิ้น
46571      ชิ้น
46572      ชิ้น

[46572 rows x 1 columns]

In [37]:
stock_uom = stock_uom.astype(str)
stock_uom

   หน่วย
0    อัน
1    คู่
2    ชุด
3   ชิ้น
4    ดวง
5  กล่อง
6    ลูก

In [38]:
def uom_mandatory_rev(df5):
    rowI = []

    for idx_row, row in df5.iterrows():
        stock_uom_finding = row['stock_uom']

        uom_check = stock_uom['หน่วย']
        uomcheck = []
        for u in uom_check:
            if u == stock_uom_finding:
                uomcheck.append(True)
            else:
                uomcheck.append(False)
        foundI = any(o == True for o in uomcheck)
        rowI.append(foundI)
        uomA = stock_uom
        if foundI:
            uomA = uomA[uomcheck]
#         print(itemcatA)
#         print(rowE)
#         if 'name' not in carC:
#             print(f"carA:{carA}")
#             print(f"carB:{carB}")
#             print(f"carC:{carC}")
#             print(f"idx_row: {idx_row}")
#             print(f"row: {row}")
#             print(f"modelth_check: {modelth_check}")

    dfI = pd.DataFrame(rowI, columns = ['stock_uom'])
    dfI['index'] = range(1, len(dfI) + 1)
    ret5 = dfI.set_index('index')
    return ret5

In [39]:
stock_uom_check = uom_mandatory_rev(uom)
stock_uom_check

       stock_uom
index
1           True
2           True
3           True
4           True
5           True
...          ...
46568       True
46569       True
46570       True
46571       True
46572       True

[46572 rows x 1 columns]

In [40]:
stock_uom_check[~stock_uom_check.all(axis=1)]

       stock_uom
index
42812      False

In [41]:
uom[~stock_uom_check.all(axis=1)]

      stock_uom
index
42812       nan

In [42]:
# cc = rev_atp.iloc[37404:37410,11:12].astype(str)
# cc = rev_atp.iloc[12507:12514,11:12].astype(str)
# cc = rev_atp.iloc[39804:39811,11:12].astype(str)
# cc = rev_atp.iloc[27740:27746,11:12].astype(str)
cc = rev_atp.iloc[:,11:12].astype(str)
cc

        CC
index
1      nan
2      nan
3      nan
4      nan
5      nan
...    ...
46568  nan
46569  nan
46570  nan
46571  nan
46572  nan

[46572 rows x 1 columns]

In [43]:
from re import search
sub = ","
sub2 = "."

In [44]:
def cc_mandatory_rev(df6):
    rowJ = []

    for idx_row, row in df6.iterrows():
        cc_check = row['CC']
        if cc_check == "nan":
            rowJ.append(True)
        else:
            if search(sub, cc_check):
                rowJ.append(False)
            else:
                if cc_check.find(sub2) != -1:
                    f = len(cc_check.split('.')[0])
                    b = len(cc_check.split('.')[1])
                    if f ==1 and b <= 2:
                        rowJ.append(True)
                    else:
                        rowJ.append(False)
                else:
                    cc_len = len(cc_check)
                    if cc_len == 1:
                        rowJ.append(True)
                    else:
                        rowJ.append(False)

    dfJ = pd.DataFrame(rowJ, columns = ['CC'])
    dfJ['index'] = range(1, len(dfJ) + 1)
    ret6 = dfJ.set_index('index')
    return ret6

In [45]:
cc_check = cc_mandatory_rev(cc)
cc_check

         CC
index
1      True
2      True
3      True
4      True
5      True
...     ...
46568  True
46569  True
46570  True
46571  True
46572  True

[46572 rows x 1 columns]

In [46]:
cc_check[~cc_check.all(axis=1)]

          CC
index
524    False
18605  False
18606  False
18607  False
27128  False
...      ...
44244  False
44245  False
44246  False
44247  False
44248  False

[318 rows x 1 columns]

In [47]:
cc[~cc_check.all(axis=1)]

              CC
index
524     1.6, 1.8
18605      1.166
18606      1.166
18607      1.166
27128      2.499
...          ...
44244  2.0L DOHC
44245  2.0L DOHC
44246  2.0L DOHC
44247  2.0L DOHC
44248  2.0L DOHC

[318 rows x 1 columns]

In [48]:
check_rev_mandatory = pd.concat([carbrand_check,item_name_check,fitment_detail_check,itembrand_check, stock_uom_check,cc_check], axis=1)
check_rev_mandatory

,car_brand,car_model,model_name_th,nickname,item_name,fitment_detail,item_brand,item_group,stock_uom,CC
index,,,,,,,,,,
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
46568,True,True,True,True,False,True,True,True,True,True
46569,True,True,True,True,False,True,True,True,True,True
46570,True,True,True,True,False,True,True,True,True,True
46571,True,True,True,True,False,True,True,True,True,True
46572,True,True,True,True,False,True,True,True,True,True

In [49]:
check_rev_mandatory_false = check_rev_mandatory[~check_rev_mandatory.all(axis=1)]
check_rev_mandatory_false

,car_brand,car_model,model_name_th,nickname,item_name,fitment_detail,item_brand,item_group,stock_uom,CC
index,,,,,,,,,,
524,True,True,True,True,True,True,True,True,True,False
1855,True,True,True,True,False,True,True,True,True,True
18605,True,True,True,True,True,True,True,True,True,False
18606,True,True,True,True,True,True,True,True,True,False
18607,True,True,True,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...
46568,True,True,True,True,False,True,True,True,True,True
46569,True,True,True,True,False,True,True,True,True,True
46570,True,True,True,True,False,True,True,True,True,True
46571,True,True,True,True,False,True,True,True,True,True
46572,True,True,True,True,False,True,True,True,True,True

In [50]:
rev_atp[~check_rev_mandatory.all(axis=1)]

,Supplier_NO.,car_brand,car_model,model_name_th,nickname,item_name,fitment_detail,description,brand,item_group,stock_uom,CC
index,,,,,,,,,,,,
524,6111689-1/T,TOYOTA,COROLLA,โคโรล่า,โฉมปี 1995-2002 (AE111),ผ้าดิสเบรค,หลัง,"COROLLA ALTIS 1996-2001 AE110, AE112 1.6L, 1.8...",GIRLING,เทียบแท้เกรด B,ชิ้น,"1.6, 1.8"
1855,NaN,TOYOTA,INNOVA,อินโนว่า,โฉมปี 2004-2015,ลูกปืน,-,ลูกปืน ในลูกรอกใหญ่,KOYO,เทียบแท้เกรด A,ชิ้น,NaN
18605,DT-004U,TOYOTA,-,-,-,จานคลัทช์,NaN,DT-004U 3K 1.166cc. 7.2' เฟือง 19T 21.6,AISIN,เทียบแท้เกรด A,ชิ้น,1.166
18606,DT-004U,TOYOTA,-,-,-,จานคลัทช์,NaN,DT-004U KE20 1.166 cc. 7.2' เฟือง 19T 21.6,AISIN,เทียบแท้เกรด A,ชิ้น,1.166
18607,DT-004U,TOYOTA,-,-,-,จานคลัทช์,NaN,DT-004U KE30 1166cc. 7.2' เฟือง 19T 21.6,AISIN,เทียบแท้เกรด A,ชิ้น,1.166
...,...,...,...,...,...,...,...,...,...,...,...,...
46568,KAG1002 (343326-D) (172207),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD (GAS),ADD,-,ชิ้น,NaN
46569,KAA-7002 (444135-D) (180187),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD(OIL),ADD,-,ชิ้น,NaN
46570,KAG2012 (344305-D) (173036),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,หน้า,โช๊คอัพ F FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น,NaN
46571,KAG2011 (344304-D) (173167),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น,NaN
46572,KAA-2002 (444136-D) (180188),FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(OIL),ADD,-,ชิ้น,NaN

In [51]:
erroroutput = []
for idx_error, error in check_rev_mandatory_false.iterrows():
    error_output = []
    error_output1 = []
    error_output2 = []
    error_output3 = []
    error_output4 = []
    error_output5 = []
    error_output6 = []
    error_output7 = []
    error_output8 = []
    error_output9 = []
    error_output10 = []
    error_output11 = []
    j = "บรรทัดที่ ", idx_error
    error_output11.append(j)
    if error['car_brand'] == False:
        a = "car_brand ไม่ตรงกับ mandatory"
        error_output1.append(a)
#     else:
#         a = ""
#         error_output1.append(a)
    if error['car_model'] == False:
        b = "car_model ไม่ตรงกับ mandatory"
        error_output2.append(b)
#     else:
#         b = ""
#         error_output2.append(b)
    if error['model_name_th'] == False:
        c = "model_name_th ไม่ตรงกับ mandatory"
        error_output3.append(c)
#     else:
#         c = " "
#         error_output3.append(c)
    if error['nickname'] == False:
        d = "nickname ไม่ตรงกับ mandatory"
        error_output4.append(d)
#     else:
#         d = " "
#         error_output4.append(d)
    if error['item_name'] == False:
        e = "item_name ไม่ตรงกับ mandatory"
        error_output5.append(e)
#     else:
#         e = " "
#         error_output5.append(e)
    if error['fitment_detail'] == False:
        f = "fitment_detail ไม่ตรงกับ mandatory"
        error_output6.append(f)
#     else:
#         f = " "
#         error_output6.append(f)    
    if error['item_brand'] == False:
        g = "item_brand ไม่ตรงกับ mandatory"
        error_output7.append(g)
#     else:
#         g = " "
#         error_output7.append(g)
    if error['item_group'] == False:
        h = "item_group ไม่ตรงกับ mandatory"
        error_output8.append(h)
#     else:
#         h = " "
#         error_output8.append(h)
    if error['stock_uom'] == False:
        i = "stock_uom ไม่ตรงกับ mandatory"
        error_output9.append(i)
#     else:
#         i = " "
#         error_output9.append(i)
    if error['CC'] == False:
        k = "ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง"
        error_output10.append(k)
#     else:
#         า = " "
#         error_output10.append(k)
    
    error_output = "บรรทัดที่ ",idx_error+2, error_output1 + error_output2 + error_output3 + error_output4 + error_output5 + error_output6 + error_output7 + error_output8 + error_output9 + error_output10
    print(error_output)
    erroroutput.append(error_output)
#     error_output.append(error_output1)
#     error_output.append(error_output2)
#     error_output.append(error_output3)
#     error_output.append(error_output4)
#     error_output.append(error_output5)
#     error_output.append(error_output6)
#     error_output.append(error_output7)
#     error_output.append(error_output8)
#     error_output.append(error_output9)
# error_output = pd.DataFrame(error_output)
# error_outputt = pd.DataFrame(error_output10)
    
#     print(idx_error, error)

('บรรทัดที่ ', 526, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 1857, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 18607, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 18608, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 18609, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 21371, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 27130, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27744, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27879, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27900, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27918, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27919, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 27920, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 28031, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 28032, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 29844, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 30298, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 30503, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 31329, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 32094, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 32197, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 32198, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 32399, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 32692, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 32971, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 33453, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 33816, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 33869, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 34540, ['ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง'])
('บรรทัดที่ ', 36931, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36932, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36933, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36934, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36935, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36936, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36937, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36938, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36939, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36940, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36941, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36942, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36943, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36944, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36945, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36946, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36947, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36948, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36949, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36950, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36951, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36952, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36953, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36954, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36955, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36956, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36957, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36958, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36960, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36961, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36962, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36963, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36965, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36966, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36967, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36968, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36969, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36970, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36971, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36972, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36973, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36974, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36975, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36976, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36977, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36978, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36979, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36980, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36981, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36982, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36983, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36985, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36986, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36987, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36988, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36989, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36990, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36991, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36992, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36993, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36994, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36995, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36996, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36997, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36998, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 36999, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37000, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37001, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37002, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37003, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37004, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37005, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37006, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37007, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37008, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37009, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37010, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37011, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37012, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37013, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37014, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37015, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37016, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37017, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37018, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37019, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37020, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37021, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37022, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37023, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37024, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37025, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37026, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37027, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37028, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37029, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37030, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37031, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37032, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37033, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37034, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37035, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37036, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37037, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37038, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37039, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37040, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37041, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37042, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37043, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37044, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37045, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37046, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37047, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37048, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37049, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37050, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37051, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37052, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37053, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37054, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37055, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37056, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37058, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37060, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37061, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37062, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37063, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37064, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37065, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37066, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37067, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37069, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37070, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37071, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37072, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37073, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37074, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37075, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37076, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37077, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37078, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37079, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37080, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37081, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37082, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37083, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37084, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37085, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 37086, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])

('บรรทัดที่ ', 40343, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40344, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40345, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40346, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40347, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40348, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40349, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40350, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40351, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40352, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40353, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40354, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40355, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40356, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40357, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40358, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40359, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40360, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40361, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40362, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40363, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40364, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40365, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40366, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40367, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40368, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40369, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40370, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40371, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40372, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40373, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40374, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40375, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40376, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40377, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40378, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40379, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40380, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40381, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40382, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40383, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40384, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40385, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40386, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40387, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40388, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40389, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40390, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40391, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40392, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40393, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40394, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40395, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40396, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40397, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40398, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40399, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40400, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40401, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40402, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40403, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40404, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40405, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40406, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40407, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40408, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40409, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40410, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40411, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40412, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40413, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40414, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40415, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40416, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40417, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40418, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40419, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40420, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40421, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40422, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40423, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40424, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40425, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40426, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40427, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40428, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40429, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40430, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40431, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40432, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40433, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40434, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40435, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40436, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40437, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40438, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40439, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40440, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40441, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40442, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40443, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40444, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40445, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40446, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40447, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40448, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40449, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40450, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40451, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40452, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40453, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40454, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40455, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40456, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40457, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40458, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40459, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40460, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40461, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40462, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40463, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40464, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40465, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40466, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40467, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40468, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40469, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40470, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40471, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40472, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40473, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40474, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40475, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40476, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40477, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40478, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40479, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40480, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40481, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40482, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40483, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40484, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40485, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40486, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40487, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40488, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40489, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40490, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40491, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40492, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40493, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40494, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40495, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40496, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40497, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40498, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40499, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40500, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40501, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40502, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40503, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40504, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40505, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40506, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40507, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40508, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40509, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40510, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40511, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40512, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40513, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40514, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40515, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40516, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40517, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40518, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40519, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40520, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40521, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40522, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40523, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40524, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40525, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40526, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40527, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40528, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40529, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40530, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40531, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40532, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40533, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40534, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40535, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40536, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40537, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40538, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40539, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40540, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40541, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40542, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40543, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40544, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40545, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40546, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40547, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40548, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40549, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40550, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40551, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40552, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40553, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40554, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40555, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40556, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40557, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40558, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40559, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40560, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40561, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40562, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40563, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40564, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40565, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40566, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40567, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40568, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40569, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40570, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40571, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40572, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40573, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40574, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40575, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40576, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40577, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40578, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40579, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40580, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40581, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40582, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40583, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40584, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40585, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40586, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40587, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40588, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40589, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40590, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40591, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40592, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40593, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40594, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40595, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40596, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40597, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40598, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40599, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40600, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40601, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40602, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40603, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40604, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40605, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40606, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40607, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40608, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40609, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40610, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40611, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40612, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40613, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40614, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40615, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40616, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40617, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40618, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40619, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40620, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40621, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40622, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40623, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40624, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40625, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40626, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40627, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40628, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40629, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40630, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40631, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40632, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40633, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40634, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40635, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40636, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40637, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40638, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40639, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40640, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40641, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40642, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40643, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40644, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40645, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40646, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40647, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40648, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40649, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40650, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40651, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40652, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40653, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40654, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40655, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40656, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40657, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40658, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40659, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40660, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40661, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40662, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40663, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40664, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40665, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40666, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40667, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40668, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40669, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40670, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40671, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40672, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40673, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40674, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40675, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40676, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40677, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40678, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40679, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40680, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40681, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40682, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40683, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40684, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40685, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40686, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40687, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40688, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40689, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40690, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40691, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 40692, ['item_name ไม่ตรงกับ mandatory'])

('บรรทัดที่ ', 41265, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41266, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41267, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41268, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41269, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41270, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41271, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41272, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41273, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41274, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41275, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41276, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41277, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41278, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41279, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41280, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41281, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41282, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41283, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41284, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41285, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41286, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41287, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41288, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41289, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41290, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41291, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41292, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41293, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41294, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41295, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41296, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41297, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41298, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41299, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41300, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41301, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41302, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41303, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41304, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41305, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41306, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41307, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41308, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41309, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41310, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41311, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41312, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41313, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41314, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41315, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41316, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41317, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41318, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41319, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41320, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41321, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41322, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41323, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41324, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41325, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41326, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41327, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41328, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41329, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41330, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41331, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41332, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41333, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41334, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41335, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41336, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41337, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41338, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41339, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41340, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41341, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41342, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41343, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41344, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41345, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41346, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41347, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41348, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41349, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41350, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41351, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41352, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41353, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41354, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41355, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41356, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41357, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41358, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41359, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41360, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41361, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41362, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41363, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41364, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41365, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41366, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41367, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41368, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41369, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41370, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41371, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41372, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41373, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41374, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41375, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41376, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41377, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41378, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41379, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41380, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41381, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41382, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41383, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41384, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41385, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41386, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41387, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41388, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41389, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41390, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41391, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41392, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41393, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41394, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41395, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41396, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41397, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41398, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41399, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41400, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41401, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41402, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41403, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41404, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41405, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41406, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41407, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41408, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41409, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41410, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41411, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41412, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41413, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41414, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41415, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41416, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41417, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41418, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41419, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41420, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41421, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41422, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41423, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41424, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41425, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41426, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41427, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41428, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41429, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41430, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41431, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41432, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41433, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41434, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41435, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41436, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41437, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41438, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41439, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41440, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41441, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41442, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41443, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41444, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41445, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41446, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41447, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41448, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41449, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41450, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41451, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41452, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41453, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41454, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41455, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41456, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41457, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41458, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41459, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41460, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41461, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41462, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41463, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41464, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41465, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41466, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41467, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41468, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41469, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41470, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41471, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41472, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41473, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41474, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41475, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41476, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41477, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41478, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41479, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41480, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41481, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41482, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41483, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41484, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41485, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41486, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41487, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41488, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41489, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41490, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41491, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41492, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41493, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41494, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41495, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41496, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41497, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41498, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41499, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41500, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41501, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41502, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41503, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41504, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41505, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41506, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41507, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41508, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41509, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41510, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41511, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41512, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41513, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41514, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41515, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41516, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41517, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41518, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41519, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41520, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41521, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41522, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41523, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41524, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41525, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41526, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41527, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41528, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41529, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41530, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41531, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41532, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41533, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41534, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41535, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41536, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41537, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41538, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41539, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41540, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41541, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41542, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41543, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41544, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41545, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41546, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41547, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41548, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41549, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41550, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41551, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41552, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41553, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41554, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41555, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41556, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41557, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41558, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41559, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41560, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41561, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41562, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41563, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41564, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41565, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41566, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41567, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41568, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41569, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41570, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41571, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41572, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41573, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41574, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41575, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41576, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41577, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41578, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41579, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41580, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41581, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41582, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41583, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41584, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41585, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41586, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41587, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41588, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41589, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41590, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41591, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41592, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41593, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41594, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41595, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41596, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41597, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41598, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41599, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41600, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41601, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41602, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41603, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41604, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41605, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41606, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41607, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41608, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41609, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41610, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41611, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41612, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 41613, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 42814, ['stock_uom ไม่ตรงกับ mandatory'])

('บรรทัดที่ ', 44690, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44691, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44692, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44693, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44694, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44695, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44696, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44697, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44698, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44699, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44700, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44701, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44702, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44703, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44704, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44705, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44706, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44707, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 44708, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45257, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45258, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45259, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45260, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45261, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45277, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45278, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45279, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45280, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45284, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45286, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45289, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45290, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45291, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45292, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45293, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45294, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45295, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45296, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45299, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45300, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45301, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45305, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45306, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45307, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45308, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45309, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45315, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45321, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45322, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45323, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45326, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45327, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45330, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45331, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45332, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45335, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45336, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45337, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45338, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45339, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45340, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45341, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45342, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45343, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45349, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45355, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45356, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45357, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45358, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45360, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45364, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45365, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45366, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45368, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45369, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45382, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45383, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45384, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45385, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45386, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45389, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45390, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45391, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45392, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45393, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45394, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45395, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45398, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45401, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45404, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45405, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45406, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45407, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45408, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45410, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45412, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45413, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45414, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45415, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45416, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45418, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45423, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45424, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45425, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45426, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45427, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45429, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45432, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45433, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45434, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45435, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45436, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45437, ['car_brand ไม่ตรงกับ mandatory', 'car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45438, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45439, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45445, ['nickname ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45446, ['nickname ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45447, ['nickname ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45448, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45449, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45450, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45454, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45455, ['car_brand ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45458, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45465, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45466, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45521, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45556, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45574, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45578, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45586, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45614, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45617, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45636, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45639, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45662, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45663, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45664, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45665, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45666, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45687, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45698, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45700, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45701, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45717, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45734, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45741, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45742, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45743, ['car_model ไม่ตรงกับ mandatory', 'model_name_th ไม่ตรงกับ mandatory', 'nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45748, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45750, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45756, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45757, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45758, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45759, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45762, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 45763, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46289, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46290, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46291, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46292, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46326, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46328, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46329, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46330, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46331, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46430, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46467, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46471, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46472, ['nickname ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46489, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46490, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46491, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46492, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46493, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46494, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46495, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46496, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46497, ['nickname ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46498, ['nickname ไม่ตรงกับ mandatory', 'item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46499, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46500, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46501, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46502, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46503, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46504, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46505, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46506, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46507, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46508, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46509, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46510, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46511, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46512, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46513, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46514, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46515, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46516, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46517, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46518, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46519, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46520, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46521, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46522, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46523, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46524, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46525, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46526, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46527, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46528, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46529, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46530, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46531, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46532, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46533, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46534, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46535, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46536, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46537, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46538, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46539, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46540, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46541, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46542, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46543, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46544, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46545, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46546, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46547, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46548, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46549, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46550, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46551, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46552, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46553, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46554, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46555, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46556, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46557, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46558, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46559, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46560, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46561, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46562, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46563, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46564, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46565, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46566, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46567, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46568, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46569, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46570, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46571, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46572, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46573, ['item_name ไม่ตรงกับ mandatory'])
('บรรทัดที่ ', 46574, ['item_name ไม่ตรงกับ mandatory'])

In [52]:
error_output = pd.DataFrame(erroroutput)
error_output

               0      1                                2
0     บรรทัดที่     526  [ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง]
1     บรรทัดที่    1857  [item_name ไม่ตรงกับ mandatory]
2     บรรทัดที่   18607  [ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง]
3     บรรทัดที่   18608  [ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง]
4     บรรทัดที่   18609  [ข้อมูลในคอลัมน์ cc ไม่ถูกต้อง]
...          ...    ...                              ...
3385  บรรทัดที่   46570  [item_name ไม่ตรงกับ mandatory]
3386  บรรทัดที่   46571  [item_name ไม่ตรงกับ mandatory]
3387  บรรทัดที่   46572  [item_name ไม่ตรงกับ mandatory]
3388  บรรทัดที่   46573  [item_name ไม่ตรงกับ mandatory]
3389  บรรทัดที่   46574  [item_name ไม่ตรงกับ mandatory]

[3390 rows x 3 columns]

In [59]:
error_output.to_excel('error_output.xlsx', index=False)

In [240]:
rev_check_duplicate = pd.read_excel('autopair_rev15.13B_forDuplicate.xlsx')
rev_check_duplicate['index'] = range(1, len(rev_check_duplicate) + 1)
rev_check_duplicate = rev_check_duplicate.set_index('index')
rev_check_duplicate

,Supplier_NO.,OEM_NO.,Benchmark_NO.,car_brand,car_model,model_name_th,nickname,Transmission,Engine Code,CC,Diesel/Bensile engine,item_name,fitment_detail,description,brand,item_group,stock_uom
index,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,AUDI,Q5,คิว5,โฉมปี 2008-2016,NaN,NaN,NaN,NaN,ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น
2,NaN,NaN,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),NaN,NaN,NaN,NaN,เบ้าโช้คอัพ/ยางเบ้าโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น
3,NaN,NaN,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2003-2010 (E60),NaN,NaN,NaN,NaN,ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น
4,NaN,NaN,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),NaN,NaN,NaN,NaN,ยางกันกระแทกโช้คอัพ,หน้า,NaN,RBI,เทียบแท้เกรด B,ชิ้น
5,NaN,NaN,NaN,BMW,SERIES 5,ซีรี่ย์5,โฉมปี 2010-2017 (F10),NaN,NaN,NaN,NaN,ไส้กรองน้ำมันเครื่อง,-,NaN,MANN,เทียบแท้เกรด A,ชิ้น
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46568,KAG1002 (343326-D) (172207),NaN,NaN,FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",2WD,NaN,NaN,NaN,โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD (GAS),ADD,-,ชิ้น
46569,KAA-7002 (444135-D) (180187),NaN,NaN,FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",2WD,NaN,NaN,NaN,โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'98 2WD(OIL),ADD,-,ชิ้น
46570,KAG2012 (344305-D) (173036),NaN,NaN,FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",4WD,NaN,NaN,NaN,โช๊คอัพ,หน้า,โช๊คอัพ F FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น
46571,KAG2011 (344304-D) (173167),NaN,NaN,FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",4WD,NaN,NaN,NaN,โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(GAS),ADD,-,ชิ้น
46572,KAA-2002 (444136-D) (180188),NaN,NaN,FORD,RANGER,แรนเจอร์,"โฉมปี 1998-2006 (2WD, ยกสูง, 4WD)",4WD,NaN,NaN,NaN,โช๊คอัพ,ขวา,โช๊คอัพ R FORD RANGER RANGER'00 4WD(OIL),ADD,-,ชิ้น

In [241]:
# rev_check_duplicate['duplicate'] = rev_check_duplicate[rev_check_duplicate.columns[:]].apply(lambda x: " ".join(x.dropna().astype(str)),axis=1)
# rev_check_duplicate['duplicate']

In [242]:
# rev_check_dup = rev_check_duplicate['duplicate']

In [243]:
duplicateRows_rev = rev_check_duplicate[rev_check_duplicate.duplicated(keep=False)]
print("All Duplicate Rows based on all columns are :")
duplicateRows_rev

All Duplicate Rows based on all columns are :

,Supplier_NO.,OEM_NO.,Benchmark_NO.,car_brand,car_model,model_name_th,nickname,Transmission,Engine Code,CC,Diesel/Bensile engine,item_name,fitment_detail,description,brand,item_group,stock_uom
index,,,,,,,,,,,,,,,,,
541,NaN,NaN,NaN,TOYOTA,COROLLA ALTIS,โคโรล่า อัลติส,โฉมปี 2008-2012 (ZZE141),NaN,NaN,NaN,NaN,คอยล์หัวเทียน,-,NaN,DENSO,เทียบแท้เกรด A,ชิ้น
759,NaN,NaN,NaN,TOYOTA,COROLLA ALTIS,โคโรล่า อัลติส,โฉมปี 2001-2007 (ZZE121),NaN,NaN,NaN,NaN,คอยล์หัวเทียน,-,NaN,DENSO,เทียบแท้เกรด A,ชิ้น
918,NaN,NaN,NaN,TOYOTA,VIOS,วีออส,"โฉมปี 2002-2007 (NCP40, 42)",NaN,NaN,NaN,NaN,คอยล์หัวเทียน,-,NaN,DENSO,เทียบแท้เกรด A,ชิ้น
1603,NaN,NaN,NaN,TOYOTA,CAMRY,คัมรี่,"โฉมปี 2006-2011 (ACV40, HYBRID)",NaN,NaN,NaN,NaN,คอยล์หัวเทียน,-,:โฉมปี 2006-2011 (ACV40),DENSO,เทียบแท้เกรด A,ชิ้น
1670,099700-243040,90919-02234,NaN,TOYOTA,CAMRY,คัมรี่,โฉมปี 2002-2006 (ACV30),NaN,NaN,NaN,NaN,คอยล์หัวเทียน,-,คอยล์จุดระเบิด TOYOTA CAMRY' 02-04,DENSO,เทียบแท้เกรด A,ชิ้น
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46380,SISENM-021,8-97247681-1,NaN,ISUZU,D-MAX,ดี-แม็กซ์,-,NaN,NaN,NaN,NaN,ยางแท่นเกียร์,NaN,D-MAX ตัวแรก 2.5/3.0 2WD 4WD (ตัว commonrail),SKR,เทียบแท้เกรด B,ชิ้น
46381,SISENM-023,8-98075376-2,NaN,ISUZU,D-MAX,ดี-แม็กซ์,-,NaN,NaN,NaN,NaN,ยางแท่นเครื่อง,ซ้าย,D-MAX 12 2.5 3.0 2WD 4WD ตัวซ้าย,SKR,เทียบแท้เกรด B,ชิ้น
46382,SISENM-023,8-98075376-2,NaN,ISUZU,D-MAX,ดี-แม็กซ์,-,NaN,NaN,NaN,NaN,ยางแท่นเครื่อง,ซ้าย,D-MAX 12 2.5 3.0 2WD 4WD ตัวซ้าย,SKR,เทียบแท้เกรด B,ชิ้น
46383,SISENM-024,8-98183242-0,NaN,ISUZU,D-MAX,ดี-แม็กซ์,-,NaN,NaN,NaN,NaN,ยางแท่นเครื่อง,ขวา,D-MAX 12 2.5 3.0 2WD 4WD ตัวขวา,SKR,เทียบแท้เกรด B,ชิ้น
46384,SISENM-024,8-98183242-0,NaN,ISUZU,D-MAX,ดี-แม็กซ์,-,NaN,NaN,NaN,NaN,ยางแท่นเครื่อง,ขวา,D-MAX 12 2.5 3.0 2WD 4WD ตัวขวา,SKR,เทียบแท้เกรด B,ชิ้น

In [244]:
duplicateRows_rev['complete'] = duplicateRows_rev[duplicateRows_rev.columns[:]].apply(lambda x: ','.join(x.dropna().astype(str)),axis=1)

<ipython-input-244-dbdff8c5c65c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicateRows_rev['complete'] = duplicateRows_rev[duplicateRows_rev.columns[:]].apply(lambda x: ','.join(x.dropna().astype(str)),axis=1)

In [245]:
duplicateRows_rev.to_csv('rev_duplicate.csv')